"""
This type stub file was generated by pyright.
"""

from .handler import Client

"client events"
class Output(Client):
    def output(self): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def wait(self): # -> None:
        ...
    


def __dir__(): # -> Literal['Output']:
    ...

