"""
This type stub file was generated by pyright.
"""

"handle events"
class Event:
    def __init__(self) -> None:
        ...
    
    def ready(self): # -> None:
        ...
    
    def reply(self, txt): # -> None:
        ...
    
    def wait(self, timeout=...): # -> None:
        ...
    


class Handler:
    def __init__(self) -> None:
        ...
    
    def callback(self, event): # -> None:
        ...
    
    def loop(self): # -> None:
        ...
    
    def poll(self):
        ...
    
    def put(self, event): # -> None:
        ...
    
    def register(self, type, callback): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    


class Client(Handler):
    def __init__(self) -> None:
        ...
    
    def announce(self, txt): # -> None:
        ...
    
    def display(self, event): # -> None:
        ...
    
    def dosay(self, channel, txt): # -> None:
        ...
    
    def raw(self, txt):
        ...
    
    def say(self, channel, txt): # -> None:
        ...
    


def __dir__(): # -> tuple[Literal['Client'], Literal['Event'], Literal['Handler']]:
    ...

