"""
This type stub file was generated by pyright.
"""

"clean namespace"
class Object:
    def __contains__(self, key): # -> bool:
        ...
    
    def __iter__(self): # -> Iterator[str]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __str__(self) -> str:
        ...
    


def construct(obj, *args, **kwargs): # -> None:
    ...

def items(obj): # -> dict_items[Any, Any]:
    ...

def keys(obj): # -> dict_keys[Any, Any]:
    ...

def update(obj, data, empty=...): # -> None:
    ...

def values(obj): # -> dict_values[Any, Any]:
    ...

def __dir__(): # -> tuple[Literal['Object'], Literal['construct'], Literal['items'], Literal['keys'], Literal['update'], Literal['values']]:
    ...

