"""
This type stub file was generated by pyright.
"""

from json import JSONEncoder

"json serializer"
class Encoder(JSONEncoder):
    def default(self, o): # -> dict_items[Any, Any] | Iterator[Any] | Any | str:
        ...
    


def dump(obj, fp, *args, **kw): # -> None:
    ...

def dumps(obj, *args, **kw): # -> str:
    ...

def __dir__(): # -> tuple[Literal['dump'], Literal['dumps'], Literal['load'], Literal['loads']]:
    ...

