"""
This type stub file was generated by pyright.
"""

import logging

"utilities"
FORMATS = ...
LEVELS = ...
class Formatter(logging.Formatter):
    def format(self, record): # -> str:
        ...
    


def check(txt): # -> bool:
    ...

def daemon(verbose=...): # -> None:
    ...

def elapsed(seconds, short=...): # -> str:
    ...

def extract_date(daystr): # -> float:
    ...

def fntime(daystr): # -> float:
    ...

def forever(): # -> None:
    ...

def importer(name, pth): # -> ModuleType | None:
    ...

def level(loglevel=...): # -> None:
    ...

def md5sum(path): # -> str:
    ...

def privileges(): # -> None:
    ...

def spl(txt): # -> list[Any]:
    ...

def __dir__(): # -> tuple[Literal['cdir'], Literal['check'], Literal['daemon'], Literal['elapsed'], Literal['extract_date'], Literal['fntime'], Literal['forever'], Literal['importer'], Literal['level'], Literal['md5sum'], Literal['privileges'], Literal['spl']]:
    ...

